version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12.2-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - rabbit_network
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: 'mysql/mysql-server:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'password!23'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'modelsDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './volumes/database:/var/lib/mysql'
    networks:
      - rabbit_network
    ports:
      - "3306:3306"


  api:
    build:
      context: ./ShuttleX_task_api
      dockerfile: Dockerfile
    networks:
      - rabbit_network
    depends_on:
      - db
      - rabbitmq

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rabbit_network
    depends_on:
      - db
      - rabbitmq
      - api
    ports:
      - "80:80"

networks:
  rabbit_network:
    driver: bridge