version: '3'
services:
  db:
    image: 'mysql/mysql-server:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'password!23'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'modelsDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './volumes/database:/var/lib/mysql'
    networks:
      - rabbit_network
    ports:
      - "3306:3306"

  api:
    build:
      context: ./ShuttleX_task_api
      dockerfile: Dockerfile
    networks:
      - rabbit_network
    depends_on:
      - db

  tests:
    build:
      context: .
      dockerfile: ./ShuttleX_task_api/ChatsControllerTests/Dockerfile
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rabbit_network
    depends_on:
      - db
      - api
    ports:
      - "80:80"

networks:
  rabbit_network:
    driver: bridge